- name: playbook
  hosts: 10.0.111.200
  become: yes

  tasks:

- name: Call Roles
  hosts: 10.0.111.200
  roles:
   #- hostname
   #- firewalld
   #- ntp-config
   #- motd   
- name: ensure apache is at the latest version
  name: httpd
  state: latest
- name: ensure apache is running
  service:
  name: httpd
  state: started
